// src/utils/exportPdf.js
// Generates a structured multi-page PDF from architecture data.
// Uses jsPDF directly (no html2canvas) for crisp, reliable output.

export async function exportToPdf(data, idea) {
  const { jsPDF } = await import('jspdf')
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })

  const PW = 210   // page width mm
  const PH = 297   // page height mm
  const ML = 18    // margin left
  const MR = 18    // margin right
  const MT = 18    // margin top
  const CW = PW - ML - MR  // content width

  // ── Light Palette ─────────────────────────────────────────────────
  const CLR = {
    bg:       [255, 255, 255], // Pure White
    surface:  [248, 250, 252], // Slate 50
    elevated: [241, 245, 249], // Slate 100
    accent:   [37,  99,  235], // Primary Blue (#2563eb)
    green:    [22,  163, 74],  // Green 600
    amber:    [217, 119, 6],   // Amber 600
    purple:   [147, 51,  234], // Purple 600
    text:     [15,  23,  42],  // Slate 900
    muted:    [71,  85,  105], // Slate 600
    faint:    [148, 163, 184], // Slate 400
    border:   [226, 232, 240], // Slate 200
  }

  let y = 0
  let page = 1

  // ── Helpers ──────────────────────────────────────────────────────

  function newPage() {
    doc.addPage()
    page++
    y = MT
    
    // Background fill
    doc.setFillColor(...CLR.bg)
    doc.rect(0, 0, PW, PH, 'F')
    
    // Footer
    doc.setFillColor(...CLR.surface)
    doc.rect(0, PH - 10, PW, 10, 'F')
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)
    doc.setTextColor(...CLR.muted)
    doc.text('InfraMind — AI Architecture Advisor', ML, PH - 3.5)
    doc.text(`Page ${page}`, PW - MR, PH - 3.5, { align: 'right' })
  }

  function checkY(needed = 20) {
    if (y + needed > PH - 16) newPage()
  }

  function sectionHeader(title, tag, color = CLR.accent) {
    checkY(20)
    // Tag pill
    doc.setFillColor(...color)
    doc.roundedRect(ML, y, 8, 5, 1, 1, 'F')
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(7)
    doc.setTextColor(...CLR.bg)
    doc.text(tag, ML + 4, y + 3.5, { align: 'center' })
    // Title
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(13)
    doc.setTextColor(...CLR.text)
    doc.text(title, ML + 12, y + 4)
    y += 10
    // Underline
    doc.setDrawColor(...color)
    doc.setLineWidth(0.4)
    doc.line(ML, y, ML + CW, y)
    y += 6
  }

  function kv(label, value, indent = 0) {
    checkY(8)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(9)
    doc.setTextColor(...CLR.muted)
    doc.text(label, ML + indent, y)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...CLR.text)
    const lines = doc.splitTextToSize(value, CW - indent - 28)
    doc.text(lines, ML + indent + 28, y)
    y += lines.length * 5 + 2
  }

  function bullet(text, indent = 0, color = CLR.accent) {
    checkY(7)
    doc.setFillColor(...color)
    doc.circle(ML + indent + 1.5, y - 1, 1, 'F')
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9)
    doc.setTextColor(...CLR.text)
    const lines = doc.splitTextToSize(text, CW - indent - 8)
    doc.text(lines, ML + indent + 6, y)
    y += lines.length * 5 + 1
  }

  function divider() {
    y += 3
    doc.setDrawColor(...CLR.border)
    doc.setLineWidth(0.2)
    doc.line(ML, y, ML + CW, y)
    y += 5
  }

  // ── COVER PAGE ────────────────────────────────────────────────────
  doc.setFillColor(...CLR.bg)
  doc.rect(0, 0, PW, PH, 'F')

  // Top accent bar
  doc.setFillColor(...CLR.accent)
  doc.rect(0, 0, PW, 1.5, 'F')

  // Logo area
  doc.setFillColor(...CLR.surface)
  doc.roundedRect(ML, 28, 40, 14, 3, 3, 'F')
  doc.setFont('courier', 'bold')
  doc.setFontSize(11)
  doc.setTextColor(...CLR.accent)
  doc.text('INFRAMIND', ML + 8, 37)

  // Title block
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(22)
  doc.setTextColor(...CLR.text)
  const titleLines = doc.splitTextToSize(data.projectTitle || idea, CW)
  doc.text(titleLines, ML, 60)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(...CLR.muted)
  const summaryLines = doc.splitTextToSize(data.projectSummary || idea, CW)
  doc.text(summaryLines, ML, 60 + titleLines.length * 10 + 6)

  // Meta box
  const metaY = 100
  doc.setFillColor(...CLR.elevated)
  doc.roundedRect(ML, metaY, CW, 30, 3, 3, 'F')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(8)
  doc.setTextColor(...CLR.muted)
  doc.text('GENERATED BY', ML + 6, metaY + 8)
  doc.text('DATE', ML + CW/2, metaY + 8)
  doc.text('STACK LAYERS', ML + CW * 0.75, metaY + 8)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(...CLR.text)
  doc.text('InfraMind AI', ML + 6, metaY + 18)
  doc.text(new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }), ML + CW/2, metaY + 18)
  doc.text(String(data.stack?.length || 0), ML + CW * 0.75, metaY + 18)

  // Idea label
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(8)
  doc.setTextColor(...CLR.muted)
  doc.text('PROJECT BRIEF', ML, 148)
  doc.setFillColor(...CLR.elevated)
  doc.roundedRect(ML, 152, CW, 20, 2, 2, 'F')
  doc.setFont('courier', 'normal')
  doc.setFontSize(9)
  doc.setTextColor(...CLR.accent)
  const ideaLines = doc.splitTextToSize(`> ${idea}`, CW - 8)
  doc.text(ideaLines, ML + 4, 160)

  // Bottom bar
  doc.setFillColor(...CLR.surface)
  doc.rect(0, PH - 14, PW, 14, 'F')
  doc.setFillColor(...CLR.accent)
  doc.rect(0, PH - 14, PW, 0.5, 'F')
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  doc.setTextColor(...CLR.muted)
  doc.text('AI-Generated Architecture Documentation', ML, PH - 6)
  doc.text('inframind.dev', PW - MR, PH - 6, { align: 'right' })

  // ── PAGE 2: TECH STACK ───────────────────────────────────────────
  newPage()
  doc.setFillColor(...CLR.bg)
  doc.rect(0, 0, PW, PH, 'F')

  sectionHeader('Recommended Tech Stack', '01', CLR.accent)

  for (const layer of (data.stack || [])) {
    const fitColor = layer.fit === 'high' ? CLR.green : layer.fit === 'medium' ? CLR.amber : CLR.muted
    const rLines = doc.splitTextToSize(layer.reason, CW - 10)
    
    // Pre-calculate card height
    let cardH = 3 + 9 + 6 + (rLines.length * 4.5 + 3)
    if (layer.alternatives?.length) {
      cardH += 6
    }
    cardH += 6 // Bottom padding
    
    checkY(cardH)
    const cardStart = y
    
    // Draw background card first!
    doc.setFillColor(...CLR.surface)
    doc.setDrawColor(...CLR.border)
    doc.setLineWidth(0.25)
    doc.roundedRect(ML - 2, cardStart, CW + 4, cardH, 2, 2, 'FD')
    
    // Left accent line
    doc.setFillColor(...fitColor)
    doc.rect(ML - 2, cardStart, 2, cardH, 'F')
    
    y += 3
    // Layer name
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(9)
    doc.setTextColor(...fitColor)
    doc.text(layer.layer.toUpperCase(), ML + 3, y + 4)

    // Fit badge
    doc.setFillColor(...fitColor)
    doc.roundedRect(ML + 3 + doc.getTextWidth(layer.layer.toUpperCase()) + 3, y + 0.5, 14, 5, 1, 1, 'F')
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(7)
    doc.setTextColor(...CLR.bg)
    doc.text(layer.fit.toUpperCase(), ML + 3 + doc.getTextWidth(layer.layer.toUpperCase()) + 10, y + 4, { align: 'center' })

    y += 9

    // Tech name
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(11)
    doc.setTextColor(...CLR.text)
    doc.text(layer.recommendation, ML + 3, y)
    y += 6

    // Reason
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8.5)
    doc.setTextColor(...CLR.muted)
    doc.text(rLines, ML + 3, y)
    y += rLines.length * 4.5 + 3

    // Alternatives
    if (layer.alternatives?.length) {
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(7.5)
      doc.setTextColor(...CLR.faint)
      doc.text('ALTERNATIVES:', ML + 3, y)
      let altX = ML + 3 + doc.getTextWidth('ALTERNATIVES:') + 3
      for (const alt of layer.alternatives) {
        const w = doc.getTextWidth(alt) + 4
        if (altX + w > ML + CW - 5) break
        doc.setFillColor(...CLR.elevated)
        doc.roundedRect(altX, y - 3.5, w, 5, 1, 1, 'F')
        doc.setFont('helvetica', 'normal')
        doc.setFontSize(7.5)
        doc.setTextColor(...CLR.muted)
        doc.text(alt, altX + 2, y)
        altX += w + 3
      }
      y += 6
    }

    y = cardStart + cardH + 5
  }

  // ── PAGE 3: API DESIGN ───────────────────────────────────────────
  newPage()
  doc.setFillColor(...CLR.bg)
  doc.rect(0, 0, PW, PH, 'F')

  sectionHeader('API Design', '02', CLR.green)

  const methodColors = {
    GET: CLR.green, POST: CLR.accent, PUT: CLR.amber,
    PATCH: CLR.amber, DELETE: [239, 68, 68], default: CLR.muted
  }

  for (let i = 0; i < (data.apis || []).length; i++) {
    const api = data.apis[i]
    checkY(12)

    // Alternating row background
    if (i % 2 === 0) {
      doc.setFillColor(...CLR.surface)
      doc.rect(ML - 2, y - 1, CW + 4, 11, 'F')
    }

    const mColor = methodColors[api.method] || methodColors.default
    const mW = 14
    doc.setFillColor(...CLR.elevated)
    doc.roundedRect(ML, y - 1, mW, 7, 1, 1, 'F')
    doc.setFont('courier', 'bold')
    doc.setFontSize(7)
    doc.setTextColor(...mColor)
    doc.text(api.method, ML + mW / 2, y + 3.5, { align: 'center' })

    // Route
    doc.setFont('courier', 'normal')
    doc.setFontSize(9)
    doc.setTextColor(...CLR.text)
    doc.text(api.route, ML + mW + 4, y + 3.5)

    // Description
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)
    doc.setTextColor(...CLR.muted)
    doc.text(api.description, PW - MR - 2, y + 3.5, { align: 'right' })

    y += 11
  }

  // ── DATABASE SCHEMA ──────────────────────────────────────────────
  y += 6
  sectionHeader('Database Schema', '03', CLR.purple)

  for (const coll of (data.dbSchema || [])) {
    // Pre-calculate card height
    let cardH = 9 + 2
    for (const field of (coll.fields || [])) {
      cardH += 7
    }
    cardH += 2
    
    checkY(cardH)
    const tStart = y

    // Draw background card first!
    doc.setFillColor(...CLR.surface)
    doc.setDrawColor(...CLR.border)
    doc.setLineWidth(0.3)
    doc.roundedRect(ML - 2, tStart, CW + 4, cardH, 2, 2, 'FD')

    // Collection header
    doc.setFillColor(...CLR.elevated)
    doc.rect(ML - 2, y, CW + 4, 9, 'F')
    doc.setFillColor(...CLR.purple)
    doc.rect(ML - 2, y, 3, 9, 'F')
    doc.setFont('courier', 'bold')
    doc.setFontSize(10)
    doc.setTextColor(...CLR.text)
    doc.text(coll.collection, ML + 5, y + 6)
    y += 11

    for (const field of (coll.fields || [])) {
      doc.setFont('courier', 'normal')
      doc.setFontSize(8.5)
      doc.setTextColor(...CLR.accent)
      doc.text(field.name, ML + 5, y)
      doc.setTextColor(...CLR.amber)
      doc.text(field.type, ML + 42, y)
      doc.setTextColor(...CLR.muted)
      doc.text(field.note || '', ML + 68, y)
      y += 7
    }

    y = tStart + cardH + 8
  }

  // ── ARCHITECTURE EXPLANATION ─────────────────────────────────────
  newPage()
  doc.setFillColor(...CLR.bg)
  doc.rect(0, 0, PW, PH, 'F')

  sectionHeader('Architecture Explanation', '04', CLR.amber)

  kv('Why this stack', data.architectureExplanation?.whyThisStack || '')
  y += 4

  if (data.architectureExplanation?.keyDecisions?.length) {
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(9)
    doc.setTextColor(...CLR.muted)
    doc.text('KEY DECISIONS', ML, y)
    y += 6
    for (const d of data.architectureExplanation.keyDecisions) {
      bullet(d, 0, CLR.amber)
    }
  }

  y += 4
  if (data.architectureExplanation?.tradeoffs?.length) {
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(9)
    doc.setTextColor(...CLR.muted)
    doc.text('TRADEOFFS', ML, y)
    y += 6
    for (const t of data.architectureExplanation.tradeoffs) {
      bullet(t, 0, CLR.amber)
    }
  }

  divider()
  sectionHeader('Scalability Notes', '05', CLR.green)

  for (const s of (data.scalability || [])) {
    const sLines = doc.splitTextToSize(s.detail, CW - 8)
    let cardH = 9 + sLines.length * 5 + 4
    
    checkY(cardH)
    const sStart = y
    
    // Draw background card first!
    doc.setFillColor(...CLR.surface)
    doc.setDrawColor(...CLR.border)
    doc.setLineWidth(0.25)
    doc.roundedRect(ML - 2, sStart, CW + 4, cardH, 2, 2, 'FD')
    
    // Left accent line
    doc.setFillColor(...CLR.green)
    doc.rect(ML - 2, sStart, 2, cardH, 'F')
    
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(10)
    doc.setTextColor(...CLR.text)
    doc.text(`${s.icon}  ${s.area}`, ML + 4, y + 5)
    y += 9
    
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8.5)
    doc.setTextColor(...CLR.muted)
    doc.text(sLines, ML + 4, y)
    
    y = sStart + cardH + 4
  }

  // ── DEPLOYMENT + ROADMAP ─────────────────────────────────────────
  newPage()
  doc.setFillColor(...CLR.bg)
  doc.rect(0, 0, PW, PH, 'F')

  sectionHeader('Deployment Strategy', '06', CLR.accent)

  const dep = data.deploymentStrategy || {}
  for (const [env, detail] of Object.entries(dep)) {
    checkY(14)
    const envColor = env === 'production' ? CLR.green : env === 'staging' ? CLR.amber : CLR.muted
    
    // Draw background card first!
    doc.setFillColor(...CLR.surface)
    doc.roundedRect(ML - 2, y, CW + 4, 14, 2, 2, 'F')
    
    // Badge
    doc.setFillColor(...envColor)
    doc.roundedRect(ML + 2, y + 3.5, 18, 6, 1, 1, 'F')
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(7)
    doc.setTextColor(...CLR.bg)
    doc.text(env.toUpperCase(), ML + 11, y + 7.5, { align: 'center' })
    
    // Text
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9)
    doc.setTextColor(...CLR.text)
    doc.text(detail, ML + 24, y + 8)
    
    y += 18
  }

  divider()
  sectionHeader('MVP Roadmap', '07', CLR.purple)

  for (const phase of (data.mvpRoadmap || [])) {
    // Pre-calculate card height
    let cardH = 11
    for (const task of (phase.tasks || [])) {
      cardH += 7
    }
    cardH += 3
    
    checkY(cardH)
    const phStart = y
    
    // Draw background card first!
    doc.setFillColor(...CLR.surface)
    doc.setDrawColor(...CLR.border)
    doc.setLineWidth(0.25)
    doc.roundedRect(ML - 2, phStart, CW + 4, cardH, 2, 2, 'FD')
    
    // Left accent line
    doc.setFillColor(...CLR.purple)
    doc.rect(ML - 2, phStart, 2, cardH, 'F')
    
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(10)
    doc.setTextColor(...CLR.purple)
    doc.text(phase.phase, ML + 4, y + 6)
    
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)
    doc.setTextColor(...CLR.muted)
    doc.text(phase.duration, ML + CW - 4, y + 6, { align: 'right' })
    y += 11
    
    for (const task of (phase.tasks || [])) {
      doc.setFillColor(...CLR.purple)
      doc.circle(ML + 7, y - 1, 0.8, 'F')
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(8.5)
      doc.setTextColor(...CLR.text)
      doc.text(task, ML + 12, y)
      y += 7
    }
    
    y = phStart + cardH + 6
  }

  // ── SAVE ─────────────────────────────────────────────────────────
  const filename = `inframind-${(data.projectTitle || idea).toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 40)}.pdf`
  doc.save(filename)
}
