// src/utils/generateScaffold.js
/**
 * Generates a downloadable .zip scaffold from an AI architecture response.
 * Uses JSZip (browser-side, no server needed).
 */
import JSZip from 'jszip'

// Map stack tech names to npm packages
const STACK_PACKAGES = {
  react:       { deps: ['react', 'react-dom'], devDeps: ['vite', '@vitejs/plugin-react'] },
  'next.js':   { deps: ['next', 'react', 'react-dom'], devDeps: [] },
  nextjs:      { deps: ['next', 'react', 'react-dom'], devDeps: [] },
  'node.js':   { deps: ['express', 'cors', 'dotenv'], devDeps: ['nodemon'] },
  nodejs:      { deps: ['express', 'cors', 'dotenv'], devDeps: ['nodemon'] },
  express:     { deps: ['express', 'cors', 'dotenv'], devDeps: ['nodemon'] },
  postgresql:  { deps: ['pg', 'pg-hstore'], devDeps: [] },
  postgres:    { deps: ['pg', 'pg-hstore'], devDeps: [] },
  mongodb:     { deps: ['mongoose'], devDeps: [] },
  redis:       { deps: ['ioredis'], devDeps: [] },
  graphql:     { deps: ['graphql', 'apollo-server-express'], devDeps: [] },
  stripe:      { deps: ['stripe'], devDeps: [] },
  auth0:       { deps: ['express-openid-connect'], devDeps: [] },
  typescript:  { deps: [], devDeps: ['typescript', 'ts-node', '@types/node'] },
  docker:      { deps: [], devDeps: [] },
  kafka:       { deps: ['kafkajs'], devDeps: [] },
  websockets:  { deps: ['socket.io'], devDeps: [] },
  'socket.io': { deps: ['socket.io'], devDeps: [] },
}

function detectPackages(stack = []) {
  const deps = new Set()
  const devDeps = new Set()
  stack.forEach(item => {
    const key = (item.recommendation || item).toLowerCase()
    Object.entries(STACK_PACKAGES).forEach(([match, pkgs]) => {
      if (key.includes(match)) {
        pkgs.deps.forEach(d => deps.add(d))
        pkgs.devDeps.forEach(d => devDeps.add(d))
      }
    })
  })
  return { deps: [...deps], devDeps: [...devDeps] }
}

function hasDocker(stack = []) {
  return stack.some(i => (i.recommendation || i).toLowerCase().includes('docker') ||
    (i.recommendation || i).toLowerCase().includes('kubernetes') ||
    (i.recommendation || i).toLowerCase().includes('aws'))
}

function generatePackageJson(data, deps, devDeps) {
  const name = (data.projectTitle || 'my-project')
    .toLowerCase().replace(/[^a-z0-9-]/g, '-').slice(0, 40)
  return JSON.stringify({
    name,
    version: '0.1.0',
    description: data.projectSummary || '',
    main: 'src/index.js',
    scripts: {
      start: 'node src/index.js',
      dev: 'nodemon src/index.js',
      build: 'echo "Configure your build step here"',
      test: 'echo "No tests yet"'
    },
    dependencies: Object.fromEntries(deps.map(d => [d, 'latest'])),
    devDependencies: Object.fromEntries(devDeps.map(d => [d, 'latest'])),
    engines: { node: '>=18.0.0' }
  }, null, 2)
}

function generateReadme(data) {
  const apis = data.apis?.map(a => `| \`${a.method}\` | \`${a.route}\` | ${a.description} |`).join('\n') || ''
  const stack = data.stack?.map(s => `- **${s.layer}**: ${s.recommendation}`).join('\n') || ''
  const decisions = data.architectureExplanation?.keyDecisions?.map(d => `- ${d}`).join('\n') || ''

  return `# ${data.projectTitle || 'Project'}

> ${data.projectSummary || ''}

Generated by [InfraMind](https://inframind.app) — AI-powered architecture design.

## Tech Stack

${stack}

## Architecture Rationale

${data.architectureExplanation?.whyThisStack || ''}

## Key Decisions

${decisions}

## API Endpoints

| Method | Route | Description |
|--------|-------|-------------|
${apis}

## Getting Started

\`\`\`bash
# Install dependencies
npm install

# Copy environment variables
cp .env.example .env

# Start development server
npm run dev
\`\`\`

## Project Structure

\`\`\`
src/
  index.js        # Application entry point
  api/
    routes.js     # API route stubs
  db/
    schema.js     # Database schema models
.env.example      # Environment variable template
\`\`\`

---
*Scaffold generated by InfraMind · [Create your own](https://inframind.app)*
`
}

function generateEnvExample(data) {
  const lines = [
    '# Environment Variables',
    '# Copy this file to .env and fill in the values',
    '',
    'NODE_ENV=development',
    'PORT=3000',
    '',
  ]

  const stack = data.stack || []
  const hasDB = stack.some(s => ['postgres', 'mongodb', 'mysql'].some(d => s.recommendation?.toLowerCase().includes(d)))
  const hasRedis = stack.some(s => s.recommendation?.toLowerCase().includes('redis'))
  const hasStripe = stack.some(s => s.recommendation?.toLowerCase().includes('stripe'))
  const hasAuth = stack.some(s => s.recommendation?.toLowerCase().includes('auth'))

  if (hasDB) {
    lines.push('# Database')
    lines.push('DATABASE_URL=postgresql://user:password@localhost:5432/mydb')
    lines.push('')
  }
  if (hasRedis) {
    lines.push('# Redis')
    lines.push('REDIS_URL=redis://localhost:6379')
    lines.push('')
  }
  if (hasStripe) {
    lines.push('# Stripe')
    lines.push('STRIPE_SECRET_KEY=sk_test_...')
    lines.push('STRIPE_WEBHOOK_SECRET=whsec_...')
    lines.push('')
  }
  if (hasAuth) {
    lines.push('# Authentication')
    lines.push('JWT_SECRET=your-super-secret-key-here')
    lines.push('AUTH_EXPIRY=7d')
    lines.push('')
  }

  lines.push('# API Keys')
  lines.push('# Add your service API keys here')

  return lines.join('\n')
}

function generateIndexJs(data) {
  return `// src/index.js — Generated by InfraMind
const express = require('express')
const cors = require('cors')
require('dotenv').config()

const app = express()
const PORT = process.env.PORT || 3000

// Middleware
app.use(cors())
app.use(express.json())

// Routes
const routes = require('./api/routes')
app.use('/api', routes)

// Health check
app.get('/health', (req, res) => {
  res.json({ status: 'ok', service: '${data.projectTitle || 'service'}', timestamp: new Date().toISOString() })
})

app.listen(PORT, () => {
  console.log(\`🚀 ${data.projectTitle || 'Server'} running on port \${PORT}\`)
})

module.exports = app
`
}

function generateRoutesJs(data) {
  const apis = data.apis || []
  const methodMap = { GET: 'get', POST: 'post', PUT: 'put', PATCH: 'patch', DELETE: 'delete' }

  const routes = apis.map(api => {
    const method = methodMap[api.method] || 'get'
    const route = api.route || '/'
    return `// ${api.description}
router.${method}('${route}', async (req, res) => {
  try {
    // TODO: Implement ${api.description}
    res.json({ success: true, data: null })
  } catch (error) {
    res.status(500).json({ error: error.message })
  }
})`
  }).join('\n\n')

  return `// src/api/routes.js — Generated by InfraMind
const express = require('express')
const router = express.Router()

${routes || '// No API routes generated'}

module.exports = router
`
}

function generateSchemaJs(data) {
  const schemas = data.dbSchema || []

  const models = schemas.map(model => {
    const fields = (model.fields || []).map(f =>
      `  ${f.name}: { type: ${mapType(f.type)}, /* ${f.note || ''} */ }`
    ).join(',\n')

    return `// ${model.collection} model
const ${model.collection}Schema = {
${fields}
}
`
  }).join('\n')

  return `// src/db/schema.js — Generated by InfraMind
// Database schemas based on AI architecture analysis
// Adapt these for your chosen ORM (Mongoose, Prisma, Sequelize, etc.)

${schemas.length > 0 ? models : '// No database schemas generated'}

module.exports = { ${schemas.map(m => m.collection + 'Schema').join(', ')} }
`
}

function mapType(type = '') {
  const t = type.toLowerCase()
  if (t.includes('string') || t.includes('text') || t.includes('varchar')) return 'String'
  if (t.includes('int') || t.includes('number') || t.includes('float')) return 'Number'
  if (t.includes('bool')) return 'Boolean'
  if (t.includes('date') || t.includes('time')) return 'Date'
  if (t.includes('object') || t.includes('json')) return 'Object'
  if (t.includes('array') || t.includes('[]')) return 'Array'
  return 'String'
}

function generateDockerCompose(data) {
  const stack = data.stack || []
  const hasPostgres = stack.some(s => s.recommendation?.toLowerCase().includes('postgres'))
  const hasRedis = stack.some(s => s.recommendation?.toLowerCase().includes('redis'))
  const hasMongo = stack.some(s => s.recommendation?.toLowerCase().includes('mongo'))
  const name = (data.projectTitle || 'project').toLowerCase().replace(/[^a-z0-9-]/g, '-')

  const services = [`  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    depends_on:
      ${hasPostgres ? '- postgres' : ''}${hasRedis ? '\n      - redis' : ''}${hasMongo ? '\n      - mongodb' : ''}`]

  if (hasPostgres) services.push(`  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${name}_db
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data`)

  if (hasRedis) services.push(`  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"`)

  if (hasMongo) services.push(`  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db`)

  const volumes = []
  if (hasPostgres) volumes.push('  postgres_data:')
  if (hasMongo) volumes.push('  mongo_data:')

  return `# docker-compose.yml — Generated by InfraMind
version: '3.9'

services:
${services.join('\n\n')}

${volumes.length ? `volumes:\n${volumes.join('\n')}` : ''}
`
}

function generateTerraformMain(data) {
  const name = (data.projectTitle || 'project').toLowerCase().replace(/[^a-z0-9-]/g, '-');
  const stack = data.stack || [];
  const hasPostgres = stack.some(s => s.recommendation?.toLowerCase().includes('postgres'));

  return `# terraform/main.tf — Generated by InfraMind
terraform {
  required_version = ">= 1.5.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.aws_region
}

# ================= VPC & Networking =================
module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "~> 5.0"

  name = "${name}-vpc"
  cidr = "10.0.0.0/16"

  azs             = ["\${var.aws_region}a", "\${var.aws_region}b"]
  private_subnets = ["10.0.1.0/24", "10.0.2.0/24"]
  public_subnets  = ["10.0.101.0/24", "10.0.102.0/24"]

  enable_nat_gateway = true
  single_nat_gateway = true
  enable_vpn_gateway = false

  tags = {
    Environment = "production"
    Project     = "${name}"
  }
}

# ================= Security Groups =================
resource "aws_security_group" "ecs_sg" {
  name        = "${name}-ecs-tasks-sg"
  description = "Allow inbound access from ALB to ECS tasks"
  vpc_id      = module.vpc.vpc_id

  ingress {
    protocol        = "tcp"
    from_port       = 3000
    to_port         = 3000
    security_groups = [aws_security_group.alb_sg.id]
  }

  egress {
    protocol    = "-1"
    from_port   = 0
    to_port     = 0
    cidr_blocks = ["0.0.0.0/0"]
  }
}

resource "aws_security_group" "alb_sg" {
  name        = "${name}-alb-sg"
  description = "Controls access to the ALB"
  vpc_id      = module.vpc.vpc_id

  ingress {
    protocol    = "tcp"
    from_port   = 80
    to_port     = 80
    cidr_blocks = ["0.0.0.0/0"]
  }

  ingress {
    protocol    = "tcp"
    from_port   = 443
    to_port     = 443
    cidr_blocks = ["0.0.0.0/0"]
  }

  egress {
    protocol    = "-1"
    from_port   = 0
    to_port     = 0
    cidr_blocks = ["0.0.0.0/0"]
  }
}

# ================= Application Load Balancer =================
resource "aws_lb" "main" {
  name               = "${name}-alb"
  subnets            = module.vpc.public_subnets
  security_groups    = [aws_security_group.alb_sg.id]
  load_balancer_type = "application"
}

resource "aws_lb_target_group" "app" {
  name        = "${name}-tg"
  port        = 3000
  protocol    = "HTTP"
  vpc_id      = module.vpc.vpc_id
  target_type = "ip"

  health_check {
    healthy_threshold   = "3"
    interval            = "30"
    protocol            = "HTTP"
    matcher             = "200"
    timeout             = "3"
    path                = "/health"
    unhealthy_threshold = "2"
  }
}

resource "aws_lb_listener" "front_end" {
  load_balancer_arn = aws_lb.main.arn
  port              = "80"
  protocol          = "HTTP"

  default_action {
    type             = "forward"
    target_group_arn = aws_lb_target_group.app.arn
  }
}

# ================= ECS Fargate Cluster & Service =================
resource "aws_ecs_cluster" "main" {
  name = "${name}-ecs-cluster"
}

resource "aws_ecs_task_definition" "app" {
  family                   = "${name}-task"
  execution_role_arn       = aws_iam_role.ecs_execution_role.arn
  task_role_arn            = aws_iam_role.ecs_task_role.arn
  network_mode             = "awsvpc"
  requires_compatibilities = ["FARGATE"]
  cpu                      = "256"
  memory                   = "512"

  container_definitions = jsonencode([{
    name      = "${name}-app"
    image     = "\${var.container_image}"
    essential = true
    portMappings = [{
      containerPort = 3000
      hostPort      = 3000
    }]
    environment = [
      { name = "NODE_ENV", value = "production" }
    ]
  }])
}

resource "aws_ecs_service" "main" {
  name            = "${name}-service"
  cluster         = aws_ecs_cluster.main.id
  task_definition = aws_ecs_task_definition.app.arn
  desired_count   = var.app_count
  launch_type     = "FARGATE"

  network_configuration {
    security_groups  = [aws_security_group.ecs_sg.id]
    subnets          = module.vpc.private_subnets
    assign_public_ip = false
  }

  load_balancer {
    target_group_arn = aws_lb_target_group.app.arn
    container_name   = "${name}-app"
    container_port   = 3000
  }

  depends_on = [aws_lb_listener.front_end]
}

# ================= IAM Roles =================
resource "aws_iam_role" "ecs_execution_role" {
  name = "${name}-ecs-execution-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action    = "sts:AssumeRole"
      Effect    = "Allow"
      Principal = { Service = "ecs-tasks.amazonaws.com" }
    }]
  })
}

resource "aws_iam_role_policy_attachment" "ecs_execution" {
  role       = aws_iam_role.ecs_execution_role.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
}

resource "aws_iam_role" "ecs_task_role" {
  name = "${name}-ecs-task-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action    = "sts:AssumeRole"
      Effect    = "Allow"
      Principal = { Service = "ecs-tasks.amazonaws.com" }
    }]
  })
}

# ================= Database (RDS PostgreSQL) =================
${hasPostgres ? `
resource "aws_security_group" "db_sg" {
  name        = "${name}-db-sg"
  description = "Allow inbound postgres access from ECS"
  vpc_id      = module.vpc.vpc_id

  ingress {
    protocol        = "tcp"
    from_port       = 5432
    to_port         = 5432
    security_groups = [aws_security_group.ecs_sg.id]
  }

  egress {
    protocol    = "-1"
    from_port   = 0
    to_port     = 0
    cidr_blocks = ["0.0.0.0/0"]
  }
}

resource "aws_db_subnet_group" "db" {
  name       = "${name}-db-subnet-group"
  subnet_ids = module.vpc.private_subnets
}

resource "aws_db_instance" "postgres" {
  identifier             = "${name}-db"
  allocated_storage      = 20
  engine                 = "postgres"
  engine_version         = "16.1"
  instance_class         = "db.t4g.micro"
  db_name                = "${name}_prod_db"
  username               = var.db_username
  password               = var.db_password
  db_subnet_group_name   = aws_db_subnet_group.db.name
  vpc_security_group_ids = [aws_security_group.db_sg.id]
  skip_final_snapshot    = true
}
` : ''}

# ================= CDN (CloudFront) =================
resource "aws_cloudfront_distribution" "cdn" {
  origin {
    domain_name = aws_lb.main.dns_name
    origin_id   = "ALBOrigin"

    custom_origin_config {
      http_port              = 80
      https_port             = 443
      origin_protocol_policy = "http-only"
      origin_ssl_protocols   = ["TLSv1.2"]
    }
  }

  enabled         = true
  is_ipv6_enabled = true
  comment         = "${name} CloudFront distribution"

  default_cache_behavior {
    allowed_methods  = ["DELETE", "GET", "HEAD", "OPTIONS", "PATCH", "POST", "PUT"]
    cached_methods   = ["GET", "HEAD"]
    target_origin_id = "ALBOrigin"

    forwarded_values {
      query_string = true
      headers      = ["*"]

      cookies {
        forward = "all"
      }
    }

    viewer_protocol_policy = "redirect-to-https"
    min_ttl                = 0
    default_ttl            = 3600
    max_ttl                = 86400
  }

  restrictions {
    geo_restriction {
      restriction_type = "none"
    }
  }

  viewer_certificate {
    cloudfront_default_certificate = true
  }

  tags = {
    Environment = "production"
  }
}
`
}

function generateTerraformVariables(data) {
  return `# terraform/variables.tf — Generated by InfraMind
variable "aws_region" {
  description = "AWS region to deploy resources"
  type        = string
  default     = "us-east-1"
}

variable "container_image" {
  description = "Docker image URL in ECR or DockerHub"
  type        = string
  default     = "nginx:alpine"
}

variable "app_count" {
  description = "Number of Docker containers to run"
  type        = number
  default     = 2
}

variable "db_username" {
  description = "Database administrator username"
  type        = string
  default     = "dbadmin"
}

variable "db_password" {
  description = "Database administrator password"
  type        = string
  sensitive   = true
  default     = "SuperSecretPassword123!"
}
`
}

function generateTerraformOutputs(data) {
  return `# terraform/outputs.tf — Generated by InfraMind
output "alb_dns_name" {
  description = "DNS name of the application load balancer"
  value       = aws_lb.main.dns_name
}

output "cloudfront_domain_name" {
  description = "DNS name of the CloudFront CDN distribution"
  value       = aws_cloudfront_distribution.cdn.domain_name
}
`
}

export async function generateScaffold(data) {
  const zip = new JSZip()
  const { deps, devDeps } = detectPackages(data.stack)

  // Root files
  zip.file('package.json', generatePackageJson(data, deps, devDeps))
  zip.file('README.md', generateReadme(data))
  zip.file('.env.example', generateEnvExample(data))
  zip.file('.gitignore', 'node_modules/\n.env\ndist/\n.DS_Store\n')

  // Source files
  const src = zip.folder('src')
  src.file('index.js', generateIndexJs(data))

  const api = src.folder('api')
  api.file('routes.js', generateRoutesJs(data))

  const db = src.folder('db')
  db.file('schema.js', generateSchemaJs(data))

  // Docker
  if (hasDocker(data.stack)) {
    zip.file('docker-compose.yml', generateDockerCompose(data))
    zip.file('Dockerfile', `FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production
COPY . .
EXPOSE 3000
CMD ["node", "src/index.js"]
`)
  }

  // Terraform IaC Folder
  const tf = zip.folder('terraform')
  tf.file('main.tf', generateTerraformMain(data))
  tf.file('variables.tf', generateTerraformVariables(data))
  tf.file('outputs.tf', generateTerraformOutputs(data))

  // Generate and download
  const blob = await zip.generateAsync({ type: 'blob', compression: 'DEFLATE' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  const name = (data.projectTitle || 'scaffold').toLowerCase().replace(/[^a-z0-9-]/g, '-')
  a.href = url
  a.download = `${name}-scaffold.zip`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
